// app/layout.tsx
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { SupabaseProvider } from "./supabase-provider";
import { Toaster } from "sonner"; // ✅ import Toaster

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });
const robotoMono = Roboto_Mono({ variable: "--font-roboto-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IT Gesit",
  description: "Generated by IT Specialist",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${robotoMono.variable}`}>
      <body className="antialiased">
        <SupabaseProvider>
          {children}
          <Toaster richColors position="top-center" /> {/* ✅ Tambahkan ini */}
        </SupabaseProvider>
      </body>
    </html>
  );
}
